### ISSUE TITLE
PostCSS support

### ISSUE THREAD

**Issue by jessedobbelaere** [getchopstick/chopstick-boilerplate#100]
> [PostCSS](https://github.com/postcss/postcss) is like Sass, but modular and capable of much more. PostCSS is, in essence, just a wrapper for plugins which exposes an easy to use, but very powerful API. While it is possible to [replicate Sass features](https://github.com/jonathantneal/precss) with PostCSS, PostCSS has an [ecosystem of amazing plugins](http://postcss.parts/) with functionalities Sass cannot even dream about having.

Fun times to be a web developer! Seems like PostCSS is getting more popular every day. 
Is PostCSS going to be on the roadmap? Using a few PostCSS plugins (mixins, precss, ...) we can probably compile the existing css code, and then we can start using the powerful possibilities of PostCSS.

**Comment by Dietr** [comment]
Not yet on the roadmap but we are watching the progress of PostCSS and are already using it for Autoprefixer so it's easy to use you preferred PostCSS plugins in your projects. But for now we are sticking with Sass for variables, mixins and functions.
