### ISSUE TITLE
Remove bower dependency

### ISSUE THREAD

**Issue by xavez** [getchopstick/chopstick-boilerplate#107]
All of the used JS dependencies are available via `npm` these days. I think we can remove the dependency on `bower` altogether. Is there a reason to keep it?

- [x] Add all JS dependencies to `package.json`.
- [x] Add `gulp` task to copy the dependencies from `node_modules/` to `vendor/`, can be done with `gulp-npm-files`.
- [x] Check paths in HTML templates.

**Comment by Wolfr** [comment]
:+1:  this was my first thought when I opened a recent Chopstick project.

**Comment by xavez** [comment]
Maybe @JonasDeGeest can check out the PR & merge :)?

**Comment by Wolfr** [comment]
I think @Dietr mentioned that the bower structure with separate parts on bower was used in existing projects so it's probably not as simple as "just" removing it.

**Comment by xavez** [comment]
@Wolfr that’s not a problem, those packages are still published on bower *and* npm and can still be accessed via either package manager.

[Read more about what this PR does](https://github.com/getchopstick/chopstick-boilerplate/pull/121)
