### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by Wolfr** [getchopstick/chopstick-boilerplate#108]
http://getchopstick.com/features talks about a mixin called "box" but this mixin doesn't exist in the codebase.

http://getchopstick.com/docs#grid talks about other mixins related to the grid but they don't seem to exist.

I suspect the framework switched to a series of utility classes combined with grid items but I can't find any documentation about these.

**Comment by jessedobbelaere** [comment]
Indeed, noticed this too. As far as I know, Chopstick was refactored to adopt BEM and ITCSS (BEMIT), but the website wasn't updated. Would be cool if it could get an update

**Comment by simoncoudeville** [comment]
Yeah, you are absolutely right. We are trying to find time to do this. Our focus is on the open issues right now. A new website is in the making but it could take some time.
