### ISSUE TITLE
Make font units variable

### ISSUE THREAD

**Issue by JonasDeGeest** [getchopstick/chopstick-boilerplate#109]
We should be able to choose between the em and rem units and maybe even px.

**Comment by xavez** [comment]
How would you propose to do this?

**Comment by JonasDeGeest** [comment]
I was thinking of implementing a setting that would define the type of unit. What do you think?

**Comment by xavez** [comment]
I don’t immediately see how I would use it, maybe you can provide an example?

**Comment by xavez** [comment]
@jonasdegeest any more input? Otherwise I'll close this in a while as it doesn't seem a priority.

**Comment by JonasDeGeest** [comment]
@xavez Question, how do you see issues being prioritized? As for your question on giving an example. With rem I'm having issues applying font scaling to certain parts of the UI. For example the body of a written article. I don't want the whole interface to scale. (see font scaling example on medium.com) Second, we should ask ourselves if rem should be the default font-unit. Which now is the case.

**Comment by xavez** [comment]
@JonasDeGeest if there is no real progress on an issue – either in the discussion or in the form of a new pull request or branch, it is probably a low priority issue that can be closed. We should probably discuss how we want to handle issues going forward, so I put it on the agenda of [points to discuss at the meetup](https://github.com/getchopstick/chopstick-boilerplate/issues/119)!

Concerning the issue at hand:

- I think an example in something like codepen or a quick screen capture probably works best to understand the issue.
- What would you propose as a better default?

**Comment by JonasDeGeest** [comment]
Hopefully following screenshot helps explaining. As you can see only parts of the font scales when screen estate expands. Creating this behaviour with rem would be harder because you would need to enlarge each element separately. As a default I would go for em as it makes scaling much easier, but that's up for discussion.
![medium](https://cloud.githubusercontent.com/assets/1419457/17528890/70039e4a-5e71-11e6-84b0-c971a533517b.jpg)

**Comment by xavez** [comment]
Made a codepen: http://codepen.io/xavez/pen/kXzJgG – does this illustrate the thing you want to achieve?

PS: I have never been a big fan of rem font-sizing, in most use cases it leads to too much codes for all the breakpoints :).

**Comment by JonasDeGeest** [comment]
Yes that's a good example. I find it hard doing this only with rem units. Hence my suggestion to make units variable. Other ideas are off course also welcome :)

**Comment by xavez** [comment]
@JonasDeGeest how would you go about making them variable, technically?

**Comment by JonasDeGeest** [comment]
@xavez Working on a PR. Haven't finished it yet but I was thinking about something like

```sass
$baseline-unit: $alpha-font-size * $alpha-line-height;
$basefontpercent: $alpha-font-size/16 * 100;
$basefontunit: em !default;
$fs: 1;
$lh: 1;

@mixin text-dimensions($fs: $alpha-font-size, $lh: $alpha-line-height, $mb: 0, $pt: 0, $pb: 0, $mt: 0) {
    font-size: #{$fs / $alpha-font-size}$basefontunit;
    line-height: #{($baseline-unit / $fs) * $lh}$basefontunit;

    @if $mb > 0 {
        @include margin-bottom($mb);
    }

    @if $mt > 0 {
        @include margin-top($mt);
    }

    @if $pt > 0 {
        @include padding-top($pt);
    }

    @if $pb > 0 {
        @include padding-bottom($pb);
    }

}
```

**Comment by xavez** [comment]
OK. Let us know when the PR is ready, I’m curious to see how this would work! :)

**Comment by xavez** [comment]
@JonasDeGeest is there a branch we can check out or do I close the issue for now?

**Comment by JonasDeGeest** [comment]
@xavez  Made a local branch from the old sass structure (seperate repo's). I'll make a new one based on the new structure. Also, I'll close this issue. We can continue our conversation when the PR is present :)
