### ISSUE TITLE
New object: column list

### ISSUE THREAD

**Issue by simoncoudeville** [getchopstick/chopstick-boilerplate#114]
To divide a list in multiple columns it's possible to use `column-count: #;` on the container and `break-inside: avoid;` on the items to prevent them from breaking up over the columns. 

This way something like this can be achieved:
![image](https://cloud.githubusercontent.com/assets/792841/15849591/a3468f02-2c93-11e6-9066-0d0ae6a99106.png)

**Comment by xavez** [comment]
@simoncoudeville were you preparing a PR for this? Otherwise I'll close the issue in a while.
