### ISSUE TITLE
Proper Crediting

### ISSUE THREAD

**Issue by xavez** [getchopstick/chopstick-boilerplate#115]
Hey everyone

I want to do this discussion in an open forum.

I appreciate that a lot of work on Chopstick is done by people who work at Wijs. However, I think it is unfair to some (myself included) to credit the entire project as a Wijs-only project. Myself (and others) have worked on Chopstick in private hours, or when working at completely different companies.

I realise a lot of code has been rewritten over time, but likewise a lot of code (and ideas) have also been reused. There are commits from different people who work at different places etc. Claiming Chopstick as a project “developed and maintained by Wijs” (on the website) is a bit of a stretch for me.

The idea of open source for me is that different people from different places can contribute in order to make something bigger than the sum of the parts. Or something bigger than any one company can create. If there is substantial input from any party, that party should be properly credited.

I would propose to:

- Either remove the website slogan altogether, or change it to “website designed by Wijs.” Which is more than fair, since Wijs did the effort of designing a fancy new website.
- Either remove the “Wijs” credits from the README.md file, or append it so it mentions all major contributors. Personal preference is not to mention any contributors in the README.md credits at all. It is much simpler and the contributors tab in GitHub and License are enough proof.
- Either remove the “Wijs” copyright from the LICENSE.md file or append it so it lists all copyright holders correctly.

Curious to learn how you think we should proceed.

**Comment by Dietr** [comment]
Hi,

Valid points and we are already working on a few .

- License: we are looking into a proper open source license (without copyright) for the moment. Will be updated asap!
- Website slogan: developed and maintained is maybe a bit too much indeed :-) but we do need some presence as a lot of Wijs budget and time has gone and will go into Chopstick. Maybe something like 'sponsored by Wijs' is more accurate?
- Readme file: similar to the website slogan?

Let me know what you think?

**Comment by fspin** [comment]
Hi, 

this is the proposal for the new license: [choosealicense.com/licenses/mpl-2.0/](http://choosealicense.com/licenses/mpl-2.0/]. It is the Mozilla Public License 2.0, and it seems fitting perfectly in Chopstick.

I will made the change in the next days, if nobody complains, of course. I hope this help. 

Kind regards.

**Comment by xavez** [comment]
- I am not sure it is possible to change the license one-sided, when some of the original code (still present in Chopstick) was written under the MIT license with different copyright holders. I think you always need consent of the [original copyright holders](https://github.com/getchopstick/chopstick-boilerplate/blob/049816de3bafb9c08c369d3f938506e73dff397a/LICENSE.md). I would propose to append the copyright notice so it correctly lists current copyright holders: either Wijs, Mono, Sophie de Brabander, Ad Eggermont. Or the entire list of full names of the major individual contributors. Another option might be to assign copyright to the FSF ([source](http://en.tldp.org/HOWTO/Software-Release-Practice-HOWTO/licensetheory.html)) with consent of all of the [original copyright holders](https://github.com/getchopstick/chopstick-boilerplate/blob/049816de3bafb9c08c369d3f938506e73dff397a/LICENSE.md). But we need input from @AdEggermont @Zofie @Dietr @simoncoudeville and @JonasDeGeest to decide that.

- I think it is OK to give people (or companies) who invested a lot in core contributions due credit. I would like to avoid however, that an open source framework becomes a content marketing tool for any single one company. Should Mono be listed as one of the sponsors because we donated coding time to the framework? Should we create different sponsor tiers with different mentions and logo sizes? I think that is probably a bit much. I’m okay with mentioning Wijs as the sole contributor to the fancy new website (which looks great!) I have an issue with mentioning them as the sole contributor and owner of the source code, because it does not reflect reality.

- Readme.md: my preference is to remove any reference to a company from this file entirely.

**Comment by jeroendesloovere** [comment]
Readme:
Integrating a link to [All contributors](https://github.com/getchopstick/chopstick-boilerplate/graphs/contributors), seems like a nice solution. Not?

**Comment by xavez** [comment]
I think that is a very good idea!

**Comment by Dietr** [comment]
Good idea indeed. Where would you put that link?

**Comment by xavez** [comment]
@Dietr I think Jeroen meant in the `readme.md`? If you agree, we can implement it quickly.

**Comment by Dietr** [comment]
Fine by me 😄

**Comment by jeroendesloovere** [comment]
👍 Yep, that was exactly what I mean't.
