### ISSUE TITLE
Html5shiv still needed?

### ISSUE THREAD

**Issue by jessedobbelaere** [getchopstick/chopstick-boilerplate#116]
```
<!-- Enable HTML5 in IE<9 -->
<!--[if lt IE 9  & (!IEMobile)]><script src="/vendor/html5shiv/dist/html5shiv.min.js"></script>
<![endif]-->
```

Not sure which legacy browsers we still support with Chopstick, but if we support >=IE9 then it's probably safe to remove html5shiv, no? Another request less for the browser to make :)

**Comment by xavez** [comment]
I think it probably makes sense to drop support for this, but curious about what others think :-)

**Comment by JonasDeGeest** [comment]
I totally agree

**Comment by Dietr** [comment]
I think our current modernizr version also includes the HTML5shiv. Maybe we should update modernizr and possibly create a custom build?

**Comment by xavez** [comment]
we built a way to customise modernizr into Bedrock. That code might be portable.
