### ISSUE TITLE
Chopstick public meetup 

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#119]
First public Chopstick meetup. Open to all current and future contributors. A day to discuss the Chopstick roadmap followed by some pair programming/coding. Please add your suggestions for the roadmap and meetup agenda as a comment.

**Date**: 15/10
**Location**: Ghent (TBD)

**Comment by Dietr** [comment]
The date will most likely be 24 september. I'll leave the doodle open so people are still welcome to join.

We still need a location. I guess Wijs is always a possibility but other suggestions are welcome.

As for the agenda. I propose the following:

### 1. General topics
Discuss some general issues which have an impact on how we use Chopstick today.
- [ ] [Confusion of design framework vs boilerplate](https://github.com/getchopstick/getchopstick.github.io/issues/7)
- [ ] [Simplify design framework partials](https://github.com/getchopstick/chopstick/issues/1)
- [ ] ...

### 2. Merge open pull requests (it would be nice to prepare pull requests for all open issues)
Merge or tweak open pull requests.
- [ ] [Remove bower as a dependency](https://github.com/getchopstick/chopstick-boilerplate/pull/121)
- [ ] ...

### 3. Review open issues on all repo's
Discuss issues that are unclear. Assign the issues that are clear.

### 4. Update roadmap. (we could aim for a 1.0 release?)

### 5. Use remaining time for some pair programming/coding

**Comment by xavez** [comment]
@Dietr I’ve updated your initial post if that’s okay :)
