### ISSUE TITLE
Remove cursor: pointer from code

### ISSUE THREAD

**Issue by xavez** [getchopstick/chopstick-boilerplate#122]
Applying `cursor: pointer` to all clickable elements might be harmful. Read more here: https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b#.7yzskuopw

`cursor: pointer` is currently applied to:

- Everything with the `.c-button` class
- `<label>`s
- `<legend>`s

I think we can remove it from `<label>`s and `<legend>`s without much discussion

The case of `.c-button` is possibly a bit more complex. For instance: `<button class="c-button">`s which do not naturally have a hand cursor, also get a hand cursor. This is not good. If anything, it should be the other way around: `.c-button`s always get a `cursor: default`. But then there are edge cases there as well.

I would propose to remove those lines of code and let the browser decide when to apply which cursor. I think they are unnecessary in the boilerplate code of chopstick.

**Comment by xavez** [comment]
Anyone has input / views on this?

**Comment by Dietr** [comment]
Good point. Maybe adding `cursor: default` to buttons also makes some sense?

**Comment by Wolfr** [comment]
Imho - don't mess with the browser defaults. Remove all of it.

**Comment by simoncoudeville** [comment]
Isn't `cursor: default` the same as removing cursor? Nevertheless I'm also in favor of removing `cursor: pointer`.

**Comment by xavez** [comment]
OK, I’ll make a PR
