### ISSUE TITLE
Use permalink: 'pretty' ?

### ISSUE THREAD

**Issue by simoncoudeville** [getchopstick/chopstick-boilerplate#132]
This way each page gets a separate folder with an index.html file -> pretty url's.

**Comment by xavez** [comment]
Good idea!

**Comment by JonasDeGeest** [comment]
Certainly a big fan of clean url's. There is also a way of handling this with .htaccess rewrite rules. Anyone tried this before?

**Comment by xavez** [comment]
@simoncoudeville make a PR and let’s implement it? 👍
