### ISSUE TITLE
Use svg symbols for icons?

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#137]
In a recent project I've used this techique: https://css-tricks.com/svg-symbol-good-choice-icons/ (icomoon also uses something similar: https://icomoon.io/#docs/inline-svg)

I liked the ease of use and it reminded me of the way icon-fonts worked. There is also a gulp plugin which will automatically generate an svg symbol from separate svg files so we could create an automated workflow for this.

Any thoughts? Other experiences?

**Comment by jessedobbelaere** [comment]
Yes please! Also started using inline svg icons way more than icon fonts. Read about several good reasons for doing this...

**Comment by xavez** [comment]
My experience is that you typically want both: SVG icons have advantages – multi colour being a big one – but also drawbacks like easy inheritance of text colour settings.

**Comment by Dietr** [comment]
I made an example of how this could work https://github.com/getchopstick/chopstick-boilerplate/tree/feature/svg-icons

It works like this:
- draw your icons in the `_artwork/icons.sketch` file
- export as svg and put them in `_artwork/symbols/`
- run `gulp symbols` or make sure `gulp watch` is running
- include the svg at the bottom of the default template
- reference the symbol by using this snippet `{% include atom.symbol.html value='icon-name' %}
- the svg will be included and follow the color and font size of the parent item

Comments, bugs, etc. are welcome!

**Comment by simoncoudeville** [comment]
Big supporter of this. The symbol defs technique has the same advantages as icon fonts but is better in terms of rendering and alignment.

**Comment by xavez** [comment]
This was fixed in #140
