### ISSUE TITLE
Increase text sizes

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#143]
The basic Chopstick theme has pretty small default text sizes.

We could increase our default text size to ~18px on mobile and 20-25px on desktop to support better legibility. (see also: https://medium.com/@xtianmiller/your-body-text-is-too-small-5e02d36dc902#.ki5fkh4l9)

**Comment by xavez** [comment]
My 2 cents: not sure if this is necessary, I think this is fairly low priority and very susceptible to personal taste – It really depends on the type of website you are building, too.

**Comment by Dietr** [comment]
I don't really agree that this is related to personal taste but low priority indeed. Will close for now.
