### ISSUE TITLE
Duplicate errLogToConsole in gulp's config.js

### ISSUE THREAD

**Issue by thibmaek** [getchopstick/chopstick-boilerplate#73]
Line 24 is an exact duplicate of line 21.
Didnt want to open a pr for this since it's easier to fix by posting an issue 😃
https://github.com/getchopstick/chopstick-boilerplate/blob/master/_gulp/config.js#L24

**Comment by Zofie** [comment]
Thanks for pointing that one out. fixing it as we speak.

**Comment by thibmaek** [comment]
Found some other errors like misplaced comma's and semicolons.
Do I make a PR or post an issue? :)

**Comment by Zofie** [comment]
Feel free to make a pull request.
