### ISSUE TITLE
Review and remove old mixins and functions

### ISSUE THREAD

**Issue by tomhudders** [getchopstick/chopstick-boilerplate#89]

**Comment by JonasDeGeest** [comment]
Mixins:
• Mediaquery mixin bestaat dubbel. Welke mixin is er van nut?
• Text color en Blockskin mixin. Schrijven we wel nog CSS?
• SVG mixin. Is die nog van toepassing?

Functions:
• EM function. Wat met REM?
• MS function. Wie gebruikt dit nog?
• SU function. Wie gebruikt dit? Nog van toepassing?
