### ISSUE TITLE
_toggle.js is too specific

### ISSUE THREAD

**Issue by JonathanDcstr** [getchopstick/chopstick-boilerplate#92]
**To specific?**
It has to 'show-and-hide' data. 

*e.g.: Can't use toggle.js to change background-color on click event.*

**Comment by jannickv** [comment]
Would it be a solution to add data-class to the trigger? Then you could define your own class that changes the background-color... if no data-class is defined it could fall back to 'is-hidden'

**Comment by jannickv** [comment]
Just created a PR to address this issue (and some other fixes). Did not change the trigger class yet for compatibility but should be updated to something like .js-toggle instead of .js-show-hide since it can do more now

https://github.com/getchopstick/chopstick-boilerplate/pull/93
