### ISSUE TITLE
Add new favicon.png and favicon.sketch source file

### ISSUE THREAD

**Issue by Dietr** [getchopstick/chopstick-boilerplate#94]

**Comment by xavez** [comment]
Can you specify the tasks to be done here?

**Comment by Dietr** [comment]
Similar to the icons.sketch file we could add a favicon.sketch file with all current sizes for touch-icons, windows tiles and favicons.

- [ ] Add favicons.sketch to /img/_source
- [ ] Update all favicons, touch icons and tiles for demo purposes

**Comment by xavez** [comment]
That’s a great idea for the boilerplate!

**Comment by xavez** [comment]
@Dietr do you know a good resource that lists all current favicon sizes? I found this: https://github.com/audreyr/favicon-cheat-sheet.

**Comment by jessedobbelaere** [comment]
I always tend to use http://realfavicongenerator.net to generate all the needed favicon sizes. Not sure if some sizes are optional though, it generates a lot of them.

**Comment by xavez** [comment]
@Dietr something like this? http://c.xvr.io/2m1c0v2z1u17/favicons.sketch

**Comment by Dietr** [comment]
Yes, a bit more extensive than I had in mind 😄 

A few questions:
- is the naming correct? Should we not call them touch-icons / apple-touch-icons / ms-touch-icon for some sizes?
- maybe we could add a master favicon symbol?

**Comment by xavez** [comment]
Feel free to upload an improved version :D

**Comment by Dietr** [comment]
Will do!

**Comment by Dietr** [comment]
Apparently the naming of the files depends on the way you include them.

There are 2 ways:
- don't link them in the head but name them like this > apple-touch-icon-*
- put links in the head and name them like this > favicon-*

Currently we are using the first technique. But the second technique seems more robust and a bit cleaner to me. More information can be found here: https://github.com/audreyr/favicon-cheat-sheet

What do you think?

**Comment by xavez** [comment]
I prefer a realistic approach: Chopstick should aim to cover most use cases, not all use cases. We’re light-weight, not complete and exhaustive.

I think it is safe to assume that in most cases, people won’t pin a Chopstick-made website to their home screen. It’s up to the designer / developer of a specific project to provide all the necessary touch icons (Android, WP etc). It’s kind of like writing a custom component for the project you’re working on.

I propose we slim down the file to the necessary icons: `favicon.ico` (16px, 24px, 32px and 64px I think) and maybe one simple apple-touch-icon* as per https://mathiasbynens.be/notes/touch-icons (scroll down to Summary).

**Comment by Dietr** [comment]
Agreed. Seems more realistic for most sites.
