### ISSUE TITLE
Update flexbox system

### ISSUE THREAD

**Issue by simoncoudeville** [getchopstick/chopstick-boilerplate#97]
Grid system met fallback 
Utitlty classes for order

**Comment by xavez** [comment]
Can you specify a bit more what needs to be done?

**Comment by JonasDeGeest** [comment]
Combining Flexbox with our gridsystem makes stuff break in some browsers (Safari) because of the clearfix. I am also curious of how other people see Flexbox. Is it a good idea to combine it with the grid system? Could it replace the grid system in some way?

**Comment by xavez** [comment]
@JonasDeGeest interesting! Can you provide an example of when it breaks? I think I’ve never been in that situation.

I personally see a grid system and flexbox as two different things: I will use flexbox for complex layouts like full height scrollable panel layouts. And I will use it for vertical alignment for instance. I will use a grid system for horizontal grid sizing. I constantly mix the two, but I would never swap one for the other entirely.

The following example is how I use it:

![](http://c.xvr.io/322x2f0m1E2q/Image%202016-07-17%20at%206.51.49%20PM.png)

**Comment by JonasDeGeest** [comment]
@xavez Interesting to see how you use Flexbox. [This post](https://blog.adriaan.io/how-clearfix-can-demolish-flexbox.html) explains the problem well. Meanwhile I bumped into [another post](http://danisadesigner.com/blog/flexbox-clear-fix-pseudo-elements/) that suggests a possible solution.

**Comment by xavez** [comment]
Can we make a PR and fix this or do we close the issue? Original post is from 2015 and we haven’t really made progress . . .

**Comment by Dietr** [comment]
I also think flexbox and a grid system are not necessarily the same thing. Personally I don't use the current flexbox object. Feels too much like a collection of utility classes for the moment.

**Comment by simoncoudeville** [comment]
They are indeed not the same thing. Flexbox can be used for a lot of other things. But I think we should update the grid system with flexbox and ditch the floats and clearfix. So that you can make for example a 2-column to 4-column grid layout with equally height columns. I'm not sure what the solution is.

On [http://www.samuraiatwork.com/nl/](http://www.samuraiatwork.com/nl/ ). I combined the two and had the issue @JonasDeGeest is referring to.

![image](https://cloud.githubusercontent.com/assets/792841/18464671/bf2f167a-7992-11e6-8309-e3e445648acf.png)

![image](https://cloud.githubusercontent.com/assets/792841/18464681/d13bc91c-7992-11e6-97f5-ead973145111.png)

**Comment by xavez** [comment]
@simoncoudeville do you have an example of a good flexbox based grid system? I usually find them overkill for a light-weight grid because flexbox can be so complicated to begin with :-).

It seems to me [CSS Grids](https://css-tricks.com/snippets/css/complete-guide-grid/) are the future of grids, and flexbox is more for a very specific type of layout. Until we have [Grid Layout](http://caniuse.com/#feat=css-grid) support, I would hold off and keep the current grid system.

**Comment by simoncoudeville** [comment]
CSS grids sure seems promising. The day we can start using this in production will definitely be a huge step forward. Until then we are stuck with other techniques.

The issue here is not making a new grid system, but improving the existing one. Instead of floats we could simply add `display: flex` to the container to "float" the children. This means we can ditch the clearfix hack and all children automatically have equal heights. Modifier classes for the grid could control how children are aligned or ordered. 

For example: reversing 2 columns while maintaining the same HTML order could be as easy as adding `.o-grid--reverse` to the grid container. This would add `flex-direction: row-reverse`

![image](https://cloud.githubusercontent.com/assets/792841/19310373/0958a83e-908a-11e6-8077-6e85668d5d8c.png)

**Comment by Dietr** [comment]
I recently used a flexbox grid in a project so I made a pull request in the chopstick-objects branch: https://github.com/getchopstick/chopstick-objects/pull/2

Although flexbox is not perfect for this, the ease of aligning grid items to the center and easily reversing the order makes it a valid solution for the time being.

Easiest way of testing this pull request is temporarily copying the _objects.grid.scss content into your vendor folder.

If we use this system, do we still need the _objects.flexbox.scss file?

**Comment by jessedobbelaere** [comment]
Saw that Bramus wrote his own flexbox grid. Might have some interesting stuff in it. 
https://www.bram.us/2016/10/07/simple-flexbox-grid-system/

**Comment by xavez** [comment]
@Dietr since that PR was made on a now obsolete repo, maybe you can re-submit your PR to the `chopstick-sass` repo?

**Comment by Dietr** [comment]
Yes, made the branch but forgot the pull request 😄 
https://github.com/getchopstick/chopstick-sass/pull/3

**Comment by xavez** [comment]
This was fixed with @Dietr’s PR!
